- id: ratchet-coverage
  name: rachet fail_under coverage requirement
  entry: ratchet-coverage
  language: python
  pass_filenames: false
  always_run: true
  require_serial: true
  files: "pyproject.toml"
  stages: [manual, pre-commit]
